# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: [develop]
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check if PR was merged
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: echo "The PR was merged!"

      - name: Check Npm -v
        run: npm -v

      - name: Set env from secrets
        run: |
          echo "DBHOST=${{ secrets.DBHOST }}" >> $GITHUB_ENV
          echo "DATABASE=${{ secrets.DATABASE }}" >> $GITHUB_ENV
          echo "DBPASSWORD=${{ secrets.DBPASSWORD }}" >> $GITHUB_ENV
          echo "DBUSER=${{ secrets.DBUSER }}" >> $GITHUB_ENV
          echo "REACT_APP_KAKAO_MAP_APP_KEY=${{ secrets.REACT_APP_KAKAO_MAP_APP_KEY }}" >> $GITHUB_ENV

      - name: create env file
        working-directory: ./
        run: |
          pwd
          touch .env
          echo DBHOST=${{ secrets.DBHOST }} >> .env
          echo DATABASE=${{ secrets.DATABASE }} >> .env
          echo DBPASSWORD=${{ secrets.DBPASSWORD }} >> .env
          echo DBUSER=${{ secrets.DBUSER }} >> .env
          echo REACT_APP_KAKAO_MAP_APP_KEY=${{ secrets.REACT_APP_KAKAO_MAP_APP_KEY }} >> .env
          cat .env

      - name: build server files
        working-directory: ./weather-data/backend/**
        run: |
          yarn
          yarn run build

      - name: zip file
        run: zip -r hous.zip ./dist ./scripts ./appspec.yml ./.env ./package.json

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./hous.zip s3://weather.tj/deploy/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name tj-code-deploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name GROUP
          --s3-location bucket=weather.tj,bundleType=zip,key=deploy/hous.zip