name: Frontend Deploy

on:
  push:
    branches: [master]
    paths:
      - 'weather-data/frontend/**' # 이 경로의 변경 사항에만 반응

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.17.0]

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: weather-data/frontend
        run: yarn install

      - name: Build frontend
        working-directory: weather-data/frontend
        run: yarn build

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload build to S3
        working-directory: weather-data/frontend
        run: aws s3 sync ./out/ s3:::weather.tj/path/
        # Note: "out" 폴더는 next.js 프로젝트의 기본 빌드 출력 폴더입니다. 실제 경로에 맞게 조정해야 할 수 있습니다.

